test_that("Dexcom-like raw export detects the reading header row", {
  path <- tempfile(fileext = ".csv")
  writeLines(c(
    "Index,Timestamp (YYYY-MM-DDThh:mm:ss),Event Type,Event Subtype,Patient Info,Device Info,Source Device ID,Glucose Value (mg/dL)",
    "1,,FirstName,,John,,,",
    "2,,LastName,,Doe,,,",
    "3,,PatientIdentifier,,08124521,,,",
    "4,,Device,,,Dexcom G7,iOS G7,",
    "5,2024-01-12T00:00:00,EGV,,,,iOS G7,341",
    "6,2024-01-12T00:05:00,EGV,,,,iOS G7,321"
  ), path)

  probe <- probe_cgm_file_import(path, "dexcom.csv")

  expect_equal(probe$profile, "Dexcom")
  expect_equal(probe$suggested_header_row, 1L)
  expect_equal(probe$suggested_first_data_row, 6L)
  expect_equal(probe$detection_status, "Ready")
})

test_that("header row and first reading row are detected separately", {
  path <- tempfile(fileext = ".csv")
  writeLines(c(
    "Index,Timestamp (YYYY-MM-DDThh:mm:ss),Event Type,Event Subtype,Patient Info,Device Info,Source Device ID,Glucose Value (mg/dL)",
    "1,,FirstName,,John,,,",
    "2,,LastName,,Joe,,,",
    "3,,PatientIdentifier,,08124521,,,",
    "4,,DateOfBirth,,10/5/1990,,,",
    "5,,Device,,,Dexcom G6,iOS G6,",
    "6,,Alert,Fall,,,iOS G6,",
    "7,,Alert,High,,,iOS G6,250",
    "8,,Alert,Low,,,iOS G6,75",
    "9,,Alert,Signal Loss,,,iOS G6,",
    "10,,Alert,Rise,,,iOS G6,",
    "11,,Alert,Urgent Low,,,iOS G6,55",
    "12,,Alert,Urgent Low Soon,,,iOS G6,55",
    "13,,Device,,,Dexcom G7,iOS G7,",
    "14,,Alert,Fall,,,iOS G7,",
    "15,,Alert,High,,,iOS G7,250",
    "16,,Alert,Low,,,iOS G7,75",
    "17,,Alert,Signal Loss,,,iOS G7,",
    "18,,Alert,Rise,,,iOS G7,",
    "19,,Alert,Urgent Low,,,iOS G7,55",
    "20,,Alert,Urgent Low Soon,,,iOS G7,55",
    "21,2024-01-12T00:00:00,EGV,,,,iOS G7,341",
    "22,2024-01-12T00:05:00,EGV,,,,iOS G7,321"
  ), path)

  probe <- probe_cgm_file_import(path, "dexcom-settings.csv")
  out <- read_cgm_file(path, "dexcom-settings.csv", header_row = 1L, first_data_row = 22L)

  expect_equal(probe$suggested_header_row, 1L)
  expect_equal(probe$suggested_first_data_row, 22L)
  expect_true("Timestamp (YYYY-MM-DDThh:mm:ss)" %in% names(out))
  expect_equal(nrow(out), 2L)
  expect_equal(out[["Glucose Value (mg/dL)"]], c(341, 321))
})

test_that("raw files with metadata before headers can be manually skipped", {
  path <- tempfile(fileext = ".csv")
  writeLines(c(
    "Report generated by CGM device",
    "Patient,Example",
    "Timestamp,Sensor Glucose (mg/dL),Notes",
    "2026-05-05 08:00:00,100,",
    "2026-05-05 08:05:00,105,"
  ), path)

  probe <- probe_cgm_file_import(path, "raw.csv")
  out <- read_cgm_file(path, "raw.csv", header_row = 3L, first_data_row = 4L)

  expect_equal(probe$suggested_header_row, 3L)
  expect_equal(probe$suggested_first_data_row, 4L)
  expect_true("Timestamp" %in% names(out))
  expect_true("Sensor Glucose (mg/dL)" %in% names(out))
  expect_equal(nrow(out), 2L)
})

test_that("Abbott and Medtronic profiles provide import hints", {
  libre <- data.frame(
    a = c("FreeStyle Libre", "Device Timestamp", "2026-05-05 08:00"),
    b = c("", "Historic Glucose mg/dL", "100"),
    stringsAsFactors = FALSE
  )
  medtronic <- data.frame(
    a = c("CareLink export", "Date", "2026-05-05"),
    b = c("MiniMed", "Sensor Glucose", "100"),
    stringsAsFactors = FALSE
  )

  expect_equal(detect_cgm_import_profile(libre), "Abbott/Libre")
  expect_equal(detect_cgm_import_profile(medtronic), "Medtronic")
})

test_that("multiple uploaded files support per-file header rows", {
  path_a <- tempfile(fileext = ".csv")
  path_b <- tempfile(fileext = ".csv")
  writeLines(c("time,glucose", "2026-05-05 08:00:00,100"), path_a)
  writeLines(c("metadata", "time,glucose", "2026-05-05 08:00:00,120"), path_b)

  combined <- combine_uploaded_files(
    c(path_a, path_b),
    c("A.csv", "B.csv"),
    header_rows = c(1L, 2L),
    first_data_rows = c(2L, 3L)
  )

  expect_equal(nrow(combined), 2L)
  expect_equal(combined$.source_id, c("A", "B"))
  expect_equal(combined$glucose, c("100", "120"))
})

test_that("invalid first reading row normalizes to after the header", {
  expect_equal(normalize_first_data_row(1L, 1L), 2L)
  expect_equal(normalize_first_data_row(3L, NA_integer_), 4L)
})

test_that("known device style fixtures detect first reading rows", {
  libre <- data.frame(
    a = c("FreeStyle Libre", "Reader", "Device Timestamp", "2026-05-05 08:00"),
    b = c("", "", "Historic Glucose mg/dL", "100"),
    stringsAsFactors = FALSE
  )
  medtronic <- data.frame(
    a = c("CareLink export", "settings", "Date", "2026-05-05 08:00"),
    b = c("MiniMed", "", "Sensor Glucose", "100"),
    stringsAsFactors = FALSE
  )

  expect_equal(detect_cgm_first_reading_row(libre, header_row = 3L, profile = "Abbott/Libre")$row, 4L)
  expect_equal(detect_cgm_first_reading_row(medtronic, header_row = 3L, profile = "Medtronic")$row, 4L)
})

test_that("incompatible resolved schemas produce a clear import message", {
  path_a <- tempfile(fileext = ".csv")
  path_b <- tempfile(fileext = ".csv")
  writeLines(c("time,glucose", "2026-05-05 08:00:00,100"), path_a)
  writeLines(c("timestamp,sensor_glucose,extra", "2026-05-05 08:00:00,120,x"), path_b)

  expect_error(
    combine_uploaded_files(c(path_a, path_b), c("A.csv", "B.csv")),
    "different resolved column names"
  )
})

test_that("preview requires timestamp and glucose mappings", {
  expect_false(required_preview_mappings_selected(NULL))
  expect_false(required_preview_mappings_selected(list(timestamp = "time", glucose = "")))
  expect_true(required_preview_mappings_selected(list(timestamp = "time", glucose = "glucose")))
})

test_that("formatted files do not need import setup", {
  path <- tempfile(fileext = ".csv")
  writeLines(c("time,glucose", "2026-05-05 08:00:00,100"), path)

  probe <- probe_cgm_file_import(path, "formatted.csv")

  expect_false(import_setup_needed(list(probe)))
  expect_equal(probe$suggested_first_data_row, 2L)
})
