// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lttb_indices_cpp
IntegerVector lttb_indices_cpp(NumericVector x, NumericVector y, int n_out);
RcppExport SEXP _CGMAnalyzerShiny_lttb_indices_cpp(SEXP xSEXP, SEXP ySEXP, SEXP n_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_out(n_outSEXP);
    rcpp_result_gen = Rcpp::wrap(lttb_indices_cpp(x, y, n_out));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CGMAnalyzerShiny_lttb_indices_cpp", (DL_FUNC) &_CGMAnalyzerShiny_lttb_indices_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CGMAnalyzerShiny(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
