#' CGMAnalyzerShiny
#'
#' Modular Shiny application for continuous glucose monitoring analysis.
#'
#' @keywords internal
#' @import data.table
"_PACKAGE"

utils::globalVariables(c(
  ".",
  ".anchor_timestamp",
  ".adapter_group",
  ".missing_sort",
  ".original_order",
  "coverage_percent",
  "calendar_x",
  "date",
  "end",
  "Expected days",
  "explicit_missing_glucose",
  "First recorded date",
  "gap_end",
  "gap_group",
  "gap_start",
  "gl",
  "glucose",
  "id",
  "imputed_flag",
  "inserted_timestamp_gap",
  "Last recorded date",
  "median",
  "Metric",
  "Metric value",
  "missing_source",
  "month",
  "Observed days",
  "percent",
  "plot_group",
  "plot_y",
  "q05",
  "q25",
  "q75",
  "q95",
  "readings",
  "Scale",
  "Scale value",
  "Sample entropy",
  "Shortfall days",
  "start",
  "status",
  "Study window status",
  "Subject ID",
  "time",
  "time_bin",
  "time_minutes",
  "timestamp",
  "tooltip",
  "Tooltip",
  "Tooltip_median",
  "Tooltip_q75",
  "Tooltip_q95",
  "unique_values",
  "Value",
  "week_index",
  "weekday",
  "xmax",
  "xmin",
  "ymax",
  "ymin"
))
